version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Run a dispatch request to trigger github action clamav scan
          command: |
            curl \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${GITHUB_TOKEN}" \
              https://api.github.com/repos/xeonproc/govwa/dispatches \
              -d '{"event_type":"clamav_malware_scan"}'

