name: Semgrep Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Semgrep
        run: |
          curl -sL https://semgrep.dev/install.sh | bash

      - name: Run Semgrep
        run: semgrep --json .
